# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ee66ccf6c4e02cfe88a38db0dc0b642e8a25d738a68d56e80b5084ba83db1e8b3d382821a7140a97c8a8139eb41a0e896d07cb5417db70a4c83d771043d2918

test:
  secret_key_base: a7a309e95a10a58f56c5a266b911e07e75d999d4b671cf9c425653ae7a641624d7961ef1f94deae51179b161d6f3ae743595f7242d931f9d7b2a1240d5bb0294

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
